### PR TITLE
[Swapping imageds between mac and windows]

### PR DESCRIPTION
**Pull request by zakariassoul**
[Swapping imageds between mac and windows]

### CODE REVIEW

**Comment by zakariassoul** [comment]
@Ankush-lastmile can you test this on your windows VM?

**Review by saqadri — COMMENTED** [review]
I don't think we should do this

**Review by saqadri — CHANGES_REQUESTED** [review]
I don't think we should do this

**Comment by zakariassoul** [comment]
Reverting changed. Will push another PR

**Pull request closed without merging**
