### PR TITLE
Merge conflict resolving Zak's big design diff stack

### PR DESCRIPTION
**Pull request by rossdanlm**
Merge conflict resolving Zak's big design diff stack

TSIA, see his orignial diff stack in https://github.com/lastmile-ai/aiconfig/pull/982

I also ran this command after to update the frontend static files from the `editor/client` directory:
```
rm -rf node_modules && yarn && yarn build
```

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/984).
* #985
* __->__ #984

### CODE REVIEW

**Comment by Ankush-lastmile** [comment]
This stack includes the vscode extension, is that ready to ship?

**Comment by rossdanlm** [comment]
> This stack includes the vscode extension, is that ready to ship?

cc @zakariassoul , @saqadri any reason not to land VSCode theming as it is now and just make updates to changes moving forwards? that way we avoid huge merge conflicts

**Comment by zakariassoul** [comment]
@rossdanlm no objection from my end. The only missing thing is side bar tweaks, and it can be shipped in a quick follow up

**Comment by rossdanlm** [comment]
Synced w. Sarmad, not going to land, only will land once everything is ready. Sarmad is handling merge conflicts on his end

**Pull request closed without merging**
