### PR TITLE
Add `log.txt` to .gitignore

### PR DESCRIPTION
**Pull request by rossdanlm**
Add `log.txt` to .gitignore

This was grinding my gears!!!!

### CODE REVIEW

**Comment by rholinshead** [comment]
Do you know where the `log.txt` file is coming from? This is more of a bandaid and we should fix whatever's creating the file because it happens with the prod vscode extension and is going to show up for all users as well

**Comment by saqadri** [comment]
What process generates the log.txt file? Does it need to be created?

**Comment by rossdanlm** [comment]
> Do you know where the log.txt file is coming from?

I don't know, just annoying for now and don't want this being generated in our repo. I created an issue to investigate: https://github.com/lastmile-ai/aiconfig/issues/1183

**Review by Ankush-lastmile — APPROVED** [review]

**Comment by Ankush-lastmile** [comment]
lets file an issue to keep track of this

**Pull request merged**
