### PR TITLE
Merge the two HuggingFace extensions into 1

### PR DESCRIPTION
**Pull request by rossdanlm**
Merge the two HuggingFace extensions into 1. I know it looks like I did a lot of line changes, but most of it was just moving files from one place to another

### CODE REVIEW

**Comment by rossdanlm** [comment]
Test plan
Screenshot 2023-12-14 at 20 49 49

Produced this image:
download

**Comment by Anpala94** [comment]
Nice image

**Review by Anpala94 — APPROVED** [review]
oops wrong account

**Review by Ankush-lastmile — APPROVED** [review]
lgtm. We're deprecating extension-huggingface-transformers then right? cc @andrew-lastmile since I know you were writing some docs

**Comment by rossdanlm** [comment]
> lgtm. We're deprecating extension-huggingface-transformers then right? cc @andrew-lastmile since I know you were writing some docs

Yes that's correct, it will all now just be `aiconfig-extension-hugging-face` which is much easier to understand now imo

**Pull request merged**
