### PR TITLE
[Style Updates]

### PR DESCRIPTION
**Pull request by zakariassoul**
[Style Updates]

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/124).
* #158
* __->__ #124

### CODE REVIEW

**Comment by zakariassoul** [comment]
Screenshot 2023-11-09 at 12 35 52 PM

Screenshot 2023-11-09 at 12 35 45 PM

**Comment by zakariassoul** [comment]
Let's merge these initial changes if they check out, and i'll push an update for the new landing page later once i have i finish some graphics

**Comment by zakariassoul** [comment]
@saqadri something failed. Any idea?

**Comment by saqadri** [comment]
I can take these changes and create a diff with them that passes the build

**Pull request closed without merging**
