### PR TITLE
Add Lint check to ci/cd

### PR DESCRIPTION
**Pull request by Ankush-lastmile**
Add Lint check to ci/cd

### CODE REVIEW

**Review by rholinshead — COMMENTED** [review]
This is just running prettier, not actually linting, right? I would expect lint with `yarn`:
```
      - name: Lint
        run: |
          yarn lint
```

**Comment by Ankush-lastmile** [comment]
> This is just running prettier, not actually linting, right? I would expect lint with yarn:

Yep, was just playing around with the github action from the marketplaces to figure out how it works. Its great and its extensible enough to be used with python and typescript. Running the python linter bubbles up 150+ exceptions 😅

**Comment by Ankush-lastmile** [comment]
> This is just running prettier, not actually linting, right? I would expect lint with yarn:

But I was trying to run linting with prettier rules, not sure if that should be done in addition to yarn lint

**Comment by Ankush-lastmile** [comment]
closing for now, will revisit later

**Pull request closed without merging**
