### PR TITLE
1/n formatting

### PR DESCRIPTION
**Pull request by Ankush-lastmile**
1/n formatting

hit cmd + s

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/784).
* #791
* #790
* __->__ #784

### CODE REVIEW

**Review by rholinshead — CHANGES_REQUESTED** [review]
I think the default extensions aren't set up but please install Prettier - Code formatter extension in VSCode for use in the client code

**Comment by Ankush-lastmile** [comment]
>please install Prettier - Code formatter extension in VSCode

I checked my vscode extensions and it looks like I have prettier installed. Do you have any global settings configured for prettier?

**Comment by Ankush-lastmile** [comment]
closing since the formatting changes are probably incorrect according to @rholinshead 's comment

**Comment by rholinshead** [comment]
> > please install Prettier - Code formatter extension in VSCode
> 
> I checked my vscode extensions and it looks like I have prettier installed. Do you have any global settings configured for prettier?

I have this in .vscode/settings.json:
```
{
  "typescript.tsdk": "node_modules/typescript/lib",
  "typescript.enablePromptUseWorkspaceTsdk": true,
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/*.code-search": true,
    "**/.next": true,
    "**/.sl": true,
    "yarn.lock": true
  },
  "editor.formatOnSave": true,
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[prisma]": {
    "editor.defaultFormatter": "Prisma.prisma"
  },
  "[python]": {
    "editor.defaultFormatter": "ms-python.black-formatter",
    "editor.formatOnSave": true,
    "editor.rulers": [150]
  },
  "black-formatter.args": ["--line-length=150"],
  // example: "--disable=C0114,C0115,C0116"
  "pylint.args": []
}

```

**Pull request closed without merging**
