### PR TITLE
Update aiconfig-editor to 0.2.2

### PR DESCRIPTION
**Pull request by rholinshead**
# Update aiconfig-editor to 0.2.2

Includes the changes from #1325 for not polling server status in readonly

### CODE REVIEW

**Review by Ankush-lastmile — APPROVED** [review]
updating the version number inside the package.json for the `aiconfig-editor` won't cause any issues right?

**Comment by rholinshead** [comment]
> will updating the version number inside the package.json for the `aiconfig-editor` cause any issues?

sorry, not entirely sure I understand. I did update the aiconfig-editor version number in its package in https://github.com/lastmile-ai/aiconfig/pull/830/files when I published the update

**Comment by Ankush-lastmile** [comment]
>sorry, not entirely sure I understand. I did update the aiconfig-editor version number in its package in https://github.com/lastmile-ai/aiconfig/pull/830/files when I published the update

Oh sorry to clarify I meant updating the version number on main instead of just that PR

**Comment by rholinshead** [comment]
> > sorry, not entirely sure I understand. I did update the aiconfig-editor version number in its package in https://github.com/lastmile-ai/aiconfig/pull/830/files when I published the update
> 
> Oh sorry to clarify I meant updating the version number on main instead of just that PR

That package only exists in that PR, not on main yet. Still quite a bit of work needed before we can merge it into main so that it exists there for development

**Pull request merged**
