### PR TITLE
Adding more install + printed commands to make it easier to setup

### PR DESCRIPTION
**Pull request by rossdanlm**
Adding more install + printed commands to make it easier to setup

This makes it more n00b friendly so people starting from scratch can use it too

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/419).
* __->__ #419
* #418

### CODE REVIEW

**Comment by rossdanlm** [comment]
The main changes I added where

1) Adding this cell
Screenshot 2023-12-06 at 14 07 13

2) Adding extra line to print the dataframe output
Screenshot 2023-12-06 at 14 07 26

**Review by jonathanlastmileai — CHANGES_REQUESTED** [review]
Thanks Rossdan! A couple of things though:

1. After the requirements fix, I don't think you need to install lastmile-utils explicitly. It should be automatically installed like all other dependencies with AIConfig.
2. For ipynb changes, please wait and rebase; I'm working on documentation as well. ipynb changes are unmergeable.

**Review by jonathanlastmileai — CHANGES_REQUESTED** [review]
Thanks @rossdanlm but please hold off on ipynb because I'm already applying changes, and ipynb changes are unmergeable.

**Comment by Ankush-lastmile** [comment]
> pynb changes are unmergeable

Are you referring to the json diffs that are hard to read?

**Comment by jonathanlastmileai** [comment]
> > 1. I don't think you need to install lastmile-utils explicitly. It should be automatically installed like all other dependencies with AIConfig
> 
> I was unable to get it to work. @Ankush-lastmile thinks this could be because I have a different Python interpreter. You can see that it imports for my python terminal editor, but not the Jupyter notebook: [#419 (comment)](https://github.com/lastmile-ai/aiconfig/pull/419#issuecomment-1843511512). You're right though this is a weird issue and I don't know why it's not working

Generally you need to make sure your Jupyter kernel points to the python executable in the right environment. I usually make a conda env and install ipykernel, which makes this pretty trivial. LMK if I can help.

**Comment by rossdanlm** [comment]
No longer needed after https://github.com/lastmile-ai/aiconfig/pull/441 landed

**Pull request closed without merging**
