### PR TITLE
Default to stream for HF model parsers

### PR DESCRIPTION
**Pull request by saqadri**
Default to stream for HF model parsers

Default stream to True if no inference options are specified.

This is the expected behavior.

Test Plan:
* Tried model parsers without this change --> no streaming

* After this change --> streaming for the same aiconfig

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/867).
* #826
* __->__ #867
* #866
* #863

### CODE REVIEW

**Review by rholinshead — APPROVED** [review]

**Review by rholinshead — CHANGES_REQUESTED** [review]
Actually, will this throw if options has no stream callback?

**Review by rholinshead — COMMENTED** [review]
Should probably do an options.stream_callback existence check before calling it

**Comment by rossdanlm** [comment]
I don't think this should be possible if we're testing from local editor. We purposefully made sure not to have streaming support if `option` isn't provided, because then that means that the InferenceOptions are malformed and not useful (ex: won't have a stream callback defined like what Ryan said). I got streaming to work yesterday on all the HF model parsers when testing using the editor, so feel free to VC and sanity check that everything is hooked up correctly!


## Technical details
Streaming is enabled as true by default from the client if it's not explicitly set in AIConfig or prompt-level settings (`enableStreaming` is undefined from https://github.com/lastmile-ai/aiconfig/blob/main/python/src/aiconfig/editor/client/src/utils/aiconfigStateUtils.ts#L21). Streaming will default to true from the editor: https://github.com/lastmile-ai/aiconfig/blob/a0362540c17a09f8481dda17ff7caf69aabfc7d6/python/src/aiconfig/editor/client/src/LocalEditor.tsx#L81

This then gets read by the server (which also defaults to true anyways if for some reason server params aren't readable) where the option is passed into the run command: https://github.com/lastmile-ai/aiconfig/blob/main/python/src/aiconfig/editor/server/server.py#L224-L238

**Review by rossdanlm — CHANGES_REQUESTED** [review]
See comment above

**Comment by saqadri** [comment]
Spoke offline with Rossdan, going to close this diff -- we will investigate if the issue comes up again

**Pull request closed without merging**
